<script setup lang="ts">
import { RESEARCH_PARAM_NAMES } from '~/types/constants'

const props = defineProps({
  paramName: {
    type: String as PropType<ResearchParamName>,
    required: true,
  },
})

const helpTexts: Record<ResearchParamName, string[]> = {
  [RESEARCH_PARAM_NAMES.COMPANY_NAME]: [
    'This is the name of the company you want the AI to research.',
    'The tool will generate queries to find information about the company.',
    'A report will be generated based on query results and the Report Schema.',
  ],
  [RESEARCH_PARAM_NAMES.INCLUDE_SEARCH_RESULTS]: [
    'This option will include search results in the report.',
    'They are the results of the execution of the queries generated by the AI',
  ],
  [RESEARCH_PARAM_NAMES.MAX_SEARCH_QUERIES]: [
    'The maximum number of queries generated by the LLM based on the schema requirements.',
  ],
  [RESEARCH_PARAM_NAMES.MAX_SEARCH_RESULTS]: [
    'The number results retrieved per query.',
    'The search results come from the Tavily API.',
  ],
  [RESEARCH_PARAM_NAMES.MAX_REFLECTION_STEPS]: [
    'The number of times the system evaluates the quality of extracted information.',
    'Continues research until information is satisfactory or max reflection steps reached.',
  ],
  [RESEARCH_PARAM_NAMES.USER_NOTES]: [
    'This is where you can add your own notes to the report.',
    'The notes will be included in the final report.',
  ],
  [RESEARCH_PARAM_NAMES.REPORT_SCHEMA]: [
    'The schema defines what information the LLM will look for.',
    'The schema is used to determine the search queries and the report structure.',
  ],
}

const helpText = computed(() => helpTexts[props.paramName])
</script>

<template>
  <div class="flex items-center space-x-2">
    <UIcon name="i-mdi-help-circle" class="text-primary w-8 h-8" />
    <div class="p-4">
      <p v-for="text in helpText" :key="text" class="text-sm">
        {{ text }}
      </p>
    </div>
  </div>
</template>
